### ISSUE TITLE
Running request throw hpts convert http HEADER to lower case

### ISSUE THREAD

**Issue by ediededi** [oyyd/http-proxy-to-socks#35]
Running request throw hpts convert http HEADER to lower case

Example : 
#Start hpts:
hpts -s socks:2910 -p 8080

#export proxy to terminal
export http_proxy=localhost:8080

#call curl 
curl --location 'remoteserver:port' --header 'UPPERCASE_HEADER: VALUE'

Expected result in remote server log : "UPPERCASE_HEADER"
Actual result: "uppercase_header"   in lower case, 
(header is used for routing and thus not working as expected)

Regards

**Comment by oyyd** [comment]
Is your remote server also a Node.js server? If so, maybe you can try get the header with `req.rawHeaders`. 

From the sender side, need some tests to check it.

**Comment by ediededi** [comment]
Hello

The remote server is an Oracle service Bus Rest Web service.
Filtering on headers is made with xquery.

The header stays in its uppercase when calling the web service without using the hpts proxy.


Regards

**Comment by oyyd** [comment]
The proxy server could get the raw headers and pass it to the downstream:

```js
const http = require('http')

const port = 12345
async function startServer() {
  const server = http.createServer()

  server.on('request', (req) => {
    console.log('req.rawHeaders', req.rawHeaders)
  })

  return new Promise((resolve, reject) => {
    server.listen(port, () => {
      resolve()
    })
  })
}

async function main() {
  await startServer()

  const req = http.request(`http://127.0.0.1:${port}`, {
    headers: {
      'UPPER-CASE': 'abc'
    }
  })

  req.end()
}

main().catch(err => {
  throw err
})
```

Then we could fix this issue by modifying the code here:
https://github.com/oyyd/http-proxy-to-socks/blob/4747645f5f4af3985c27f17158f79eb42548c6a5/src/proxy_server.js#L48

**Comment by oyyd** [comment]
Hi, @ediededi can you help to try if this version works for you?

```bash
npx http-proxy-to-socks@beta
```

**Comment by ediededi** [comment]
Hello and thank you for your reply, this actually works, the headers stays in it original case.

**Comment by oyyd** [comment]
Thanks for the test! I'm will merge the request and publish the latest tag version.
